# Set the default logging level to DEBUG
org.slf4j.simpleLogger.defaultLogLevel=debug

# Optional: Show the thread name and date
org.slf4j.simpleLogger.showThreadName=true
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS